import { useQuery } from "@tanstack/react-query";
import { ArrowUpRight, BrainCircuit, ChevronRight, CircleAlert, Clock3, MailCheck, ShieldCheck, TrendingUp } from "lucide-react";
import { Link } from "react-router-dom";
import { apiGet } from "@/lib/api";
import type { OverviewResponse } from "@/types/mailmind";
import AppShell from "@/components/layout/AppShell";
import Sparkline from "@/components/charts/Sparkline";
import { CategoryBadge, PriorityBadge, SpamBadge } from "@/components/mailmind/StatusBadge";

const kpis = [
  { key: "spam_detected", label: "Spam & suspicious", icon: ShieldCheck, suffix: "flagged", tone: "cyan", spark: [30, 41, 35, 52, 48, 64, 59] },
  { key: "high_priority", label: "High priority", icon: CircleAlert, suffix: "needs attention", tone: "violet", spark: [26, 31, 28, 42, 40, 48, 55] },
  { key: "action_required", label: "Needs a reply", icon: Clock3, suffix: "open", tone: "amber", spark: [35, 29, 41, 38, 48, 43, 52] },
  { key: "phishing_risk", label: "Unsafe emails", icon: BrainCircuit, suffix: "review", tone: "rose", spark: [17, 23, 21, 32, 27, 36, 29] },
] as const;

function LineChart({ data }: { data: OverviewResponse["volume_trend"] }) {
  if (!data.length) return <div className="line-chart" data-testid="overview-volume-chart" />;
  const max = data.length ? Math.max(...data.map((point) => point.value)) : 0;
  const span = Math.max(1, data.length - 1);
  const points = data.map((point, index) => `${(index / span) * 100},${100 - (point.value / (max || 1)) * 80}`).join(" ");
  return <div className="line-chart" data-testid="overview-volume-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><defs><linearGradient id="lineFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#62e6f5" stopOpacity=".24" /><stop offset="100%" stopColor="#62e6f5" stopOpacity="0" /></linearGradient></defs><polygon points={`0,100 ${points} 100,100`} fill="url(#lineFill)" /><polyline points={points} fill="none" stroke="#62e6f5" strokeWidth="1.5" /></svg><div className="chart-axis">{data.map((point) => <span key={point.label}>{point.label.replace("May ", "")}</span>)}</div></div>;
}

export default function Dashboard() {
  const { data, isError, isLoading } = useQuery({ queryKey: ["overview"], queryFn: () => apiGet<OverviewResponse>("/overview") });
  return <AppShell><div className="page-stack" data-testid="dashboard-page">
    <div className="page-heading"><div><div className="eyebrow"><span className="live-dot" /> Live intelligence workspace</div><h1>Good morning <span className="wave">✦</span></h1><p>Here’s what MailMind discovered across your analyzed emails.</p></div><div className="heading-actions"><Link to="/analyze" className="button-primary" data-testid="dashboard-analyze-button"><MailCheck size={16} /> Analyze new email</Link><button className="button-secondary" data-testid="dashboard-upload-button">Upload emails <ArrowUpRight size={15} /></button></div></div>
    {isError && <div className="inline-error" data-testid="dashboard-error">The intelligence service is unavailable. The workspace shell is still available.</div>}
    <section className="overview-grid">
      <div className="hero-metric-panel panel" data-testid="email-intelligence-panel"><div className="panel-topline"><span className="eyebrow">Email intelligence</span><span className="ai-active"><span /> AI analysis active</span></div><div className="hero-metric"><div><strong>{isLoading ? "—" : data?.emails_analyzed.toLocaleString()}</strong><span>Emails analyzed</span></div><div className="metric-change"><TrendingUp size={14} /> <small>across your analyzed emails</small></div></div><LineChart data={data?.volume_trend ?? []} /></div>
      <div className="health-panel panel" data-testid="email-health-panel"><div className="panel-topline"><span className="eyebrow">Email health</span><span className="health-label">Good standing</span></div><div className="health-ring"><div><strong>{data?.inbox_health ?? "—"}</strong><span>/ 100</span></div></div><div className="health-copy">Your inbox is focused, with a few signals worth reviewing.</div><div className="health-breakdown">{(data?.health_breakdown ?? ["Loading health signals..."]).map((item) => <div key={item}><span className="check-mark">✓</span>{item}</div>)}</div></div>
    </section>
    <section className="kpi-grid" data-testid="kpi-grid">{kpis.map(({ key, label, icon: Icon, suffix, tone, spark }) => <Link to={key === "spam_detected" || key === "phishing_risk" ? "/spam" : "/inbox"} className={`kpi-card panel tone-${tone}`} key={key} data-testid={`kpi-card-${key}`}><div className="kpi-icon"><Icon size={16} /></div><div className="kpi-label">{label}<ArrowUpRight size={13} /></div><strong>{isLoading ? "—" : data?.[key].toLocaleString()}</strong><div className="kpi-foot"><span>{suffix}</span><Sparkline values={spark} color={tone === "violet" ? "#a88bff" : tone === "amber" ? "#f8c56a" : tone === "rose" ? "#ff8b9b" : "#62e6f5"} /></div></Link>)}</section>
    <section className="analytics-grid"><div className="panel distribution-panel" data-testid="priority-distribution-panel"><div className="section-heading"><div><span className="eyebrow">Signal overview</span><h2>Priority distribution</h2></div><button className="quiet-button" data-testid="priority-view-all-button">View all <ChevronRight size={14} /></button></div><div className="bar-list">{(data?.priority_distribution ?? []).map((item) => <div className="bar-item" key={item.label}><div className="bar-label"><span>{item.label}</span><strong>{item.value}</strong></div><div className="bar-track"><i style={{ width: `${Math.max(3, (item.value / Math.max(1, Math.max(...(data?.priority_distribution ?? [{ value: 1 }]).map((entry) => Number(entry.value))))) * 100)}%` }} /></div></div>)}</div></div><div className="panel category-panel" data-testid="category-distribution-panel"><div className="section-heading"><div><span className="eyebrow">Semantic map</span><h2>Email categories</h2></div><span className="panel-meta">{data?.emails_analyzed ?? 0} emails</span></div><div className="category-chart"><div className="donut"><div><strong>{data?.emails_analyzed ?? 0}</strong><span>emails</span></div></div><div className="legend-list">{(data?.category_distribution ?? []).slice(0, 6).map((item, index) => <div key={item.label}><span className={`legend-dot dot-${index}`} />{item.label}<strong>{item.value}</strong></div>)}</div></div></div></section>
    <section className="panel recent-panel" data-testid="recent-analysis-panel"><div className="section-heading"><div><span className="eyebrow">Latest signals</span><h2>Recent analysis</h2></div><Link to="/inbox" className="quiet-button" data-testid="recent-view-inbox-button">Open inbox <ChevronRight size={14} /></Link></div><div className="recent-table"><div className="recent-head"><span>Sender / subject</span><span>Category</span><span>Priority</span><span>Security</span><span>Confidence</span><span /></div>{!isLoading && !data?.recent_analysis.length && <div className="empty-state" data-testid="recent-empty-state"><strong>No analyzed emails yet</strong><span>Your AI inbox is waiting.</span><Link to="/analyze" className="button-secondary">Analyze your first email</Link></div>}{(data?.recent_analysis ?? []).slice(0, 5).map((email) => <Link to={`/inbox/${email.id}`} className="recent-row" key={email.id} data-testid={`recent-email-${email.id}`}><div className="recent-sender"><div className="sender-avatar">{email.sender.split(" ").map((part) => part[0]).join("").slice(0, 2)}</div><div><strong>{email.sender}</strong><span>{email.subject}</span></div></div><CategoryBadge value={email.category} /><PriorityBadge value={email.priority} /><SpamBadge value={email.spam_status} /><span className="confidence-number">{email.confidence}%</span><ArrowUpRight size={15} /></Link>)}</div></section>
  </div></AppShell>;
}