import { useQuery } from "@tanstack/react-query";
import { ChevronLeft, ChevronRight, Filter, RefreshCw, Search, SlidersHorizontal } from "lucide-react";
import { useState } from "react";
import { apiGet } from "@/lib/api";
import type { EmailListResponse } from "@/types/mailmind";
import AppShell from "@/components/layout/AppShell";
import EmailTable from "@/components/mailmind/EmailTable";

const filters = [{ value: "all", label: "All mail" }, { value: "priority", label: "Priority" }, { value: "action", label: "Action required" }, { value: "spam", label: "Spam" }, { value: "suspicious", label: "Suspicious" }];

export default function Inbox() {
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("all");
  const { data, isLoading, isError, refetch } = useQuery({ queryKey: ["emails", search, filter], queryFn: () => apiGet<EmailListResponse>(`/emails?search=${encodeURIComponent(search)}&filter=${filter}`) });
  return <AppShell><div className="page-stack" data-testid="inbox-page"><div className="page-heading compact"><div><div className="eyebrow">Workspace / Inbox</div><h1>Inbox intelligence</h1><p>Every message classified, prioritized, and ready for a human decision.</p></div><div className="inbox-total"><strong>{data?.total.toLocaleString() ?? "2,430"}</strong><span>emails in demo index</span></div></div><div className="demo-banner subtle" data-testid="inbox-demo-banner"><span><span className="banner-dot" /> Simulated demo dataset</span><span>Showing model-shaped email records for presentation</span></div><div className="inbox-toolbar panel"><div className="inbox-search"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search senders, subjects, previews..." data-testid="inbox-search-input" /></div><button className="toolbar-button" data-testid="inbox-filter-button"><Filter size={15} /> Filters</button><button className="toolbar-button" onClick={() => void refetch()} data-testid="inbox-refresh-button"><RefreshCw size={15} /> Refresh</button></div><div className="filter-tabs" role="tablist" data-testid="inbox-filter-tabs">{filters.map((item) => <button className={filter === item.value ? "selected" : ""} key={item.value} onClick={() => setFilter(item.value)} data-testid={`inbox-filter-${item.value}`}>{item.label}{item.value === "all" && <span>2.4k</span>}</button>)}</div>{isError && <div className="inline-error" data-testid="inbox-error">Unable to load email intelligence right now.</div>}<div className="table-meta"><span>{isLoading ? "Loading intelligence..." : `${data?.total ?? 0} messages found`}</span><span><SlidersHorizontal size={14} /> Sorted by latest analysis</span></div><EmailTable emails={data?.items ?? []} /><div className="pagination"><span>Showing {data?.items.length ?? 0} of {data?.total ?? 0}</span><div><button data-testid="pagination-previous"><ChevronLeft size={15} /></button><span className="page-number">1</span><button data-testid="pagination-next"><ChevronRight size={15} /></button></div></div></div></AppShell>;
}